stages:
  - build
  - test

cache:
  paths:


build-bdd:
  image: docker:latest
  stage: build
  services:
  - docker:dind    
  script:
    - echo \" BUILD BDD\"
    - cd docker/dev
    - docker-compose up -d
    
build-job:
  image:  maven:3.6.3-openjdk-8
  stage: build
  script:
    - echo \" BUILD\"
    - mvn compile -f src


test-business:
  services:
  - docker:dind 
  image:  maven:3.6.3-openjdk-8
  stage: test
  script:
    - cd docker/dev
    - apk add --no-cache docker-compose
    - docker-compose up -d
    - echo \" TEST-BUSINESS\"
    - mvn verify -f src -P test-business

test-consumer:
  image:  maven:3.6.3-openjdk-8
  stage: test
  script:
    - echo \" TEST-CONSUMER\"
    - mvn test -f src -P test-consumer
