image: maven:3.6.1-jdk-8-alpine

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository/



build-job:
  stage: build
  script:
    - echo \" BUILD\"
    - mvn compile -f src


test-business:
  stage: test
  script:
    - echo \" TEST-BUSINESS\"
    - mvn test -f src -P test-business

test-consumer:
  stage: test
  script:
    - echo \" TEST-CONSUMER\"
    - mvn test -f src -P test-consumer

