image: docker:latest

services:
- docker:dind

before_script:
- cd docker/dev
- apk add docker-compose
- docker-compose up -d

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository


    
build-job:
  image:  maven:3.6.3-openjdk-8
  stage: build
  script:
    - echo \" BUILD\"
    - mvn compile -f src


test-business:
  image:  maven:3.6.3-openjdk-8
  stage: test
  script:
    - echo \" TEST-BUSINESS\"
    - cat myerp-database.gz
    - mvn  verify -f src -P test-business

test-consumer:
  image:  maven:3.6.3-openjdk-8
  stage: test
  script:
    - echo \" TEST-CONSUMER\"
    - mvn verify -f src -P test-consumer
