stages:
  - build
  - test

cache:
  paths:
    - .m2/repository/


before-script:
  image: docker:latest
services:
  - docker:dind    
script:
    - echo \" BUILD BDD\"
    - cd docker/dev
    - apk add --no-cache docker-compose
    - docker-compose up -d
    
build-job:
  image:  maven:3.6.3-openjdk-8
  stage: build
  script:
    - echo \" BUILD\"
    - mvn compile -f src


test-business:
  image:  maven:3.6.3-openjdk-8
  stage: test
  script:
    - echo \" TEST-BUSINESS\"
    - mvn test -f src -P test-business

test-consumer:
  image:  maven:3.6.3-openjdk-8
  stage: test
  script:
    - echo \" TEST-CONSUMER\"
    - mvn test -f src -P test-consumer
