stages:
  - build
  - test

cache:
  paths:
    - .m2/repository

build-bdd:
  image: docker:latest
  stage: build
  services:
  - docker:dind    
  script:
    - echo \" BUILD BDD\"
    - cd docker/dev
    - apk add --no-cache docker-compose
    - docker-compose up -d
  artifacts:
    paths :
      - myerp-database
    
build-job:
  image:  maven:3.6.3-openjdk-8
  stage: build
  script:
    - echo \" BUILD\"
    - mvn compile -f src


test-business:
  image:  maven:3.6.3-openjdk-8
  stage: test
  script:
    - echo \" TEST-BUSINESS\"
    - cat myerp-database
    - mvn  verify -f src -P test-business

test-consumer:
  image:  maven:3.6.3-openjdk-8
  stage: test
  script:
    - echo \" TEST-CONSUMER\"
    - mvn verify -f src -P test-consumer
