image: jtim/docker-docker-compose-jdk-mvn:18.09.1-ce-git-compose-1.23.1-openjdk-8u191-maven-3.6.0
services: 
    - docker:dind
stages:
  - build
  - test

cache:
  paths:
    - .m2/repository


before_script:
    - cd docker/dev
    - apk add --no-cache docker-compose
    - docker-compose up -d
    
build-job:
  stage: build
  script:
    - echo \" BUILD\"
    - mvn compile -f src


test-business:
  stage: test
  script:
    - echo \- TEST-BUSINESS\"
    - mvn verify -P test-business

test-consumer:
  stage: test
  script:
    - echo \" TEST-CONSUMER\"
    - mvn verify -f src -P test-consumer
