stages:
  - build
  - test

cache:
  paths:
    - .m2/repository

build-bdd:
  image: docker:latest
  services: 
    - docker:dind
  stage: build
  script:
    - cd docker/dev
    - apk add docker-compose
    - docker-compose up -d
    
build-job:
  image:  docker
  stage: build
  script:
    - echo \" upILD\"
    - mvn compile -f src


test-business:
  image: jtim/docker-docker-compose-jdk:20.10.2-compose-1.28.0-openjdk-8u252 
  stage: test
  services :
    - docker:dind
  script:
    - echo \- TEST-BUSINESS\"
    - docker/dev
    - docker-compose up -d
    - cd..
    - cd..
    - mvn  verify -f src -P test-business

test-consumer:
  image:  maven:3.6.3-openjdk-8
  stage: test
  script:
    - echo \" TEST-CONSUMER\"
    - mvn verify -f src -P test-consumer
