language: java

jdk: openjdk8

services:
  - docker


before_script:
  - cd docker/dev
  - docker-compose up -d 
  - cd ../..

script:
  - mvn verify -f src sonar:sonar -P test-business
  - mvn verify -f src sonar:sonar -P test-consumer


notifications:
email: false
