language: java

dist: xenial

jdk: openjdk8

services:
  - docker
  
addons:
  sonarcloud:
    organization: "vancharlotte" # the key of the org you chose at step #3
    token:
      secure : travis encrypt 19d5e566ab2f60a4ae60be07e28f7a6a259b8476  # encrypted value of your token


before_script:
  - cd docker/dev
  - docker-compose up -d 
  - cd ../..

script:
  - mvn verify -f src sonar:sonar -P test-business
  - mvn verify -f src sonar:sonar -P test-consumer
  
 cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'


